name: Update Splade.dev

on:
  push:
    branches:
      - main

jobs:
  update:

    runs-on: ubuntu-latest

    steps:
    - name: Update docs
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://splade.dev/update-docs?signature=${{ secrets.UPDATE_DOCS_TOKEN }}'
        method: 'GET'
